"""Render a v1.0 ``domain-map`` JSON as a GitHub-renderable mermaid diagram.

The input is whatever :mod:`rtl_buddy_cdc.domain_map` produces (or whatever
a previous ``--emit-domain-map`` run wrote to disk). This renderer never
touches the analyzer pipeline — it's a pure function on the parsed JSON
dict, mirroring the discipline of :mod:`rtl_buddy_cdc.reporter`.

The output groups flops by clock domain (one ``subgraph`` per clock),
draws async crossings as dashed warning edges, and surfaces top-level
ports as stadium nodes feeding the matching-clock flop. Everything is
sorted so a golden-file diff against the same input is empty.

See issue #162 for the design discussion + sketches.
"""

from __future__ import annotations

import hashlib
from io import StringIO
from typing import Any

SUPPORTED_SCHEMA_MAJOR = 1


class RenderError(ValueError):
    """Raised when the input JSON is not a v1.0 domain map."""


def render_mermaid(map_data: dict[str, Any]) -> str:
    """Return a fenced ```mermaid``` block for ``map_data``.

    ``map_data`` must be a parsed v1.0 domain map (see
    :mod:`rtl_buddy_cdc.domain_map`). Only the major schema version is
    checked; minor drift (new optional fields) is tolerated.
    """
    _check_schema(map_data)
    top = map_data.get("design", {}).get("top", "design")

    clocks = _all_clocks(map_data)
    flops_by_clock = _group_flops_by_clock(map_data.get("flop_domains", []))
    ports = sorted(
        map_data.get("port_domains", []),
        key=lambda p: (p.get("clock", ""), p.get("port", "")),
    )
    crossings = sorted(
        map_data.get("crossings", []),
        key=lambda c: (
            c.get("src_flop", ""),
            c.get("dst_flop", ""),
            c.get("src_clock", ""),
            c.get("dst_clock", ""),
        ),
    )

    buf = StringIO()
    buf.write("```mermaid\n")
    buf.write(f"%% {top} — generated by rtl-buddy-cdc render\n")
    buf.write("flowchart LR\n")

    # Clock subgraphs (deterministic order: name).
    for clk in clocks:
        clk_name = clk["name"]
        sg_id = _clock_subgraph_id(clk_name)
        header = _clock_header(clk)
        buf.write(f'  subgraph {sg_id}["{header}"]\n')
        buf.write("    direction TB\n")
        for fd in flops_by_clock.get(clk_name, []):
            node_id = _flop_node_id(fd["instance_path"])
            label = _flop_label(fd, top)
            buf.write(f'    {node_id}["{label}"]\n')
        buf.write("  end\n")

    # Orphan flops (clock not in clocks/generated_clocks) — keep them
    # visible rather than silently dropping. Group under a synthetic
    # subgraph so it's obvious they're not in a declared clock.
    known = {c["name"] for c in clocks}
    orphans = [c for c in sorted(flops_by_clock) if c and c not in known]
    for clk_name in orphans:
        sg_id = _clock_subgraph_id(clk_name)
        buf.write(f'  subgraph {sg_id}["{clk_name} (undeclared)"]\n')
        buf.write("    direction TB\n")
        for fd in flops_by_clock[clk_name]:
            node_id = _flop_node_id(fd["instance_path"])
            label = _flop_label(fd, top)
            buf.write(f'    {node_id}["{label}"]\n')
        buf.write("  end\n")

    # Ports.
    for port in ports:
        port_id = _port_node_id(port["port"], port.get("kind", "input"))
        kind = port.get("kind", "input")
        marker = "in" if kind == "input" else "out"
        buf.write(f'  {port_id}[/"{port["port"]}⟨{marker}⟩"/]:::port\n')

    # Port → flop edges. A port drives every flop in its declared clock
    # domain whose instance is in the top module — we don't have a
    # netlist-level fanout map here, so this is a coarse-but-honest
    # signal that the port belongs to that clock cluster.
    for port in ports:
        if port.get("kind") != "input":
            continue
        port_id = _port_node_id(port["port"], "input")
        # Pick the first flop in the clock as the visual anchor — it's
        # a documentation aid, not a connectivity claim.
        anchor = _first_flop_in_clock(flops_by_clock, port.get("clock"))
        if anchor is not None:
            buf.write(f"  {port_id} --> {_flop_node_id(anchor)}\n")

    # Crossings.
    for x in crossings:
        src = x.get("src_flop")
        dst = x.get("dst_flop")
        if not src or not dst:
            continue
        src_id = _flop_node_id(src)
        dst_id = _flop_node_id(dst)
        width = x.get("width", 1)
        if x.get("async_per_sdc"):
            buf.write(f'  {src_id} -. "⚠ async · {width}b" .-> {dst_id}\n')
        else:
            buf.write(f"  {src_id} --- {dst_id}\n")

    buf.write("  classDef port fill:#f4f4f5,stroke:#71717a\n")
    buf.write("```\n")
    return buf.getvalue()


# --- helpers ----------------------------------------------------------------


def _check_schema(map_data: dict[str, Any]) -> None:
    sv = str(map_data.get("schema_version", ""))
    if not sv:
        raise RenderError("input is missing 'schema_version'")
    major = sv.split(".", 1)[0]
    if major != str(SUPPORTED_SCHEMA_MAJOR):
        raise RenderError(
            f"unsupported domain-map schema major {major!r}; "
            f"this renderer understands v{SUPPORTED_SCHEMA_MAJOR}.x"
        )


def _all_clocks(map_data: dict[str, Any]) -> list[dict[str, Any]]:
    """Concatenate ``clocks`` and ``generated_clocks``, sorted by name.

    Generated clocks fall through with whatever fields they carry — we
    only ever read ``name`` and ``period`` so missing keys are fine.
    """
    out = list(map_data.get("clocks", [])) + list(map_data.get("generated_clocks", []))
    out.sort(key=lambda c: str(c.get("name", "")))
    return out


def _group_flops_by_clock(
    flops: list[dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    by_clock: dict[str, list[dict[str, Any]]] = {}
    for fd in flops:
        clk = fd.get("clock") or ""
        by_clock.setdefault(clk, []).append(fd)
    for clk in by_clock:
        by_clock[clk].sort(key=lambda e: str(e.get("instance_path", "")))
    return by_clock


def _clock_header(clk: dict[str, Any]) -> str:
    name = clk.get("name", "?")
    period = clk.get("period")
    if isinstance(period, (int, float)):
        return f"{name} · {period} ns"
    return str(name)


def _clock_subgraph_id(clock_name: str) -> str:
    return "clk_" + _safe_id(clock_name)


def _flop_node_id(instance_path: str) -> str:
    # Mermaid node ids must be id-like; instance paths contain ``$`` /
    # ``.`` / ``/`` which are unsafe. Hash for collision-resistance,
    # short prefix for human-greppability.
    h = hashlib.sha256(instance_path.encode("utf-8")).hexdigest()[:8]
    return f"f_{h}"


def _port_node_id(port_name: str, kind: str) -> str:
    return f"p_{kind[:2]}_{_safe_id(port_name)}"


def _safe_id(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    if not out or not (out[0].isalpha() or out[0] == "_"):
        out.insert(0, "_")
    return "".join(out)


def _flop_label(fd: dict[str, Any], top: str) -> str:
    path = str(fd.get("instance_path", "?"))
    # Strip the top module prefix to keep labels short. ``top.foo.bar``
    # becomes ``foo.bar``; the lone top stays as-is.
    prefix = f"{top}."
    short = path[len(prefix) :] if path.startswith(prefix) else path
    loc = fd.get("location") or {}
    line = loc.get("start_line")
    if isinstance(line, int):
        return f"{short}<br/><i>sv:{line}</i>"
    return short


def _first_flop_in_clock(
    flops_by_clock: dict[str, list[dict[str, Any]]],
    clock_name: str | None,
) -> str | None:
    if not clock_name:
        return None
    entries = flops_by_clock.get(clock_name)
    if not entries:
        return None
    return str(entries[0].get("instance_path", ""))
