"""Render a v1.0 ``domain-map`` JSON as a GitHub-renderable mermaid diagram.

The input is whatever :mod:`rtl_buddy_cdc.domain_map` produces (or whatever
a previous ``--emit-domain-map`` run wrote to disk). This renderer never
touches the analyzer pipeline — it's a pure function on the parsed JSON
dict, mirroring the discipline of :mod:`rtl_buddy_cdc.reporter`.

The output groups flops by clock domain (one ``subgraph`` per clock),
draws async crossings as dashed warning edges, and surfaces top-level
ports as stadium nodes feeding the matching-clock flop. Everything is
sorted so a golden-file diff against the same input is empty.

See issue #162 for the design discussion + sketches.
"""

from __future__ import annotations

import hashlib
from io import StringIO
from typing import Any

SUPPORTED_SCHEMA_MAJOR = 1

# Per-clock fill/stroke palette. Light pastels stay readable on both
# GitHub light + dark themes; the strong stroke carries the domain
# identity if the fill washes out in dark mode. Assigned to clocks in
# sorted-name order, cycling if a design has more than the palette.
_CLOCK_PALETTE: list[tuple[str, str]] = [
    ("#e0f2fe", "#0369a1"),  # sky
    ("#fef3c7", "#b45309"),  # amber
    ("#d1fae5", "#047857"),  # emerald
    ("#ffe4e6", "#be123c"),  # rose
    ("#ede9fe", "#6d28d9"),  # violet
    ("#fce7f3", "#a21caf"),  # fuchsia
]
_FALLBACK_FILL = "#f4f4f5"
_FALLBACK_STROKE = "#71717a"


class RenderError(ValueError):
    """Raised when the input JSON is not a v1.0 domain map."""


def render_mermaid(map_data: dict[str, Any]) -> str:
    """Return a fenced ```mermaid``` block for ``map_data``.

    ``map_data`` must be a parsed v1.0 domain map (see
    :mod:`rtl_buddy_cdc.domain_map`). Only the major schema version is
    checked; minor drift (new optional fields) is tolerated.
    """
    _check_schema(map_data)
    top = map_data.get("design", {}).get("top", "design")

    clocks = _all_clocks(map_data)
    flops_by_clock = _group_flops_by_clock(map_data.get("flop_domains", []))
    ports = sorted(
        map_data.get("port_domains", []),
        key=lambda p: (p.get("clock", ""), p.get("port", "")),
    )
    crossings = sorted(
        map_data.get("crossings", []),
        key=lambda c: (
            c.get("src_flop", ""),
            c.get("dst_flop", ""),
            c.get("src_clock", ""),
            c.get("dst_clock", ""),
        ),
    )

    # Assign a color class to each clock name (declared + undeclared).
    # Sorted-name order keeps assignments stable across runs of the
    # same design and predictable across the bad/good fixture pairs.
    known = {c["name"] for c in clocks}
    orphans = [c for c in sorted(flops_by_clock) if c and c not in known]
    palette_order = [c["name"] for c in clocks] + orphans
    clock_class = {name: _clock_class_name(name) for name in palette_order}

    # Group ports by their declared clock so they sit inside the same
    # subgraph as the flops they belong with. Ports whose SDC-declared
    # clock is unknown (or absent) stay outside every cluster.
    ports_by_clock: dict[str, list[dict[str, Any]]] = {}
    unclocked_ports: list[dict[str, Any]] = []
    for port in ports:
        pclk = port.get("clock")
        if pclk and pclk in clock_class:
            ports_by_clock.setdefault(pclk, []).append(port)
        else:
            unclocked_ports.append(port)

    buf = StringIO()
    buf.write("```mermaid\n")
    buf.write(f"%% {top} — generated by rtl-buddy-cdc render\n")
    buf.write("flowchart LR\n")

    # Clock subgraphs (deterministic order: name). Each subgraph
    # contains the ports typed to this clock plus the flops Yosys
    # traced into this clock.
    for clk in clocks:
        clk_name = clk["name"]
        sg_id = _clock_subgraph_id(clk_name)
        header = _clock_header(clk)
        cls = clock_class[clk_name]
        buf.write(f'  subgraph {sg_id}["{header}"]\n')
        buf.write("    direction TB\n")
        for port in ports_by_clock.get(clk_name, []):
            _emit_port_line(buf, port, cls, indent="    ")
        for fd in flops_by_clock.get(clk_name, []):
            node_id = _flop_node_id(fd["instance_path"])
            label = _flop_label(fd, top)
            buf.write(f'    {node_id}["{label}"]:::{cls}\n')
        buf.write("  end\n")

    # Orphan flops (clock not in clocks/generated_clocks) — keep them
    # visible rather than silently dropping. Group under a synthetic
    # subgraph so it's obvious they're not in a declared clock.
    for clk_name in orphans:
        sg_id = _clock_subgraph_id(clk_name)
        cls = clock_class[clk_name]
        buf.write(f'  subgraph {sg_id}["{clk_name} (undeclared)"]\n')
        buf.write("    direction TB\n")
        for port in ports_by_clock.get(clk_name, []):
            _emit_port_line(buf, port, cls, indent="    ")
        for fd in flops_by_clock[clk_name]:
            node_id = _flop_node_id(fd["instance_path"])
            label = _flop_label(fd, top)
            buf.write(f'    {node_id}["{label}"]:::{cls}\n')
        buf.write("  end\n")

    # Untyped ports (no `set_input_delay` / `set_output_delay`, not on
    # a `create_clock` port list) — emit outside every cluster with
    # the fallback grey.
    for port in unclocked_ports:
        _emit_port_line(buf, port, "port_unassigned", indent="  ")

    # Edge index counter — mermaid ``linkStyle`` directives target
    # edges by 0-indexed declaration order, so we track each edge as
    # it lands in the buffer to colour the clock-network ones below.
    edge_idx = 0

    # Crossings. Source is either a flop (the typical register-to-
    # register case) or a top-level port that the SDC typed with
    # ``set_input_delay -clock`` — render both with the same edge
    # styling so reviewers can spot async hops regardless of origin.
    for x in crossings:
        dst = x.get("dst_flop")
        if not dst:
            continue
        src_flop = x.get("src_flop")
        src_port = x.get("src_port")
        if src_flop:
            src_id = _flop_node_id(src_flop)
        elif src_port:
            src_id = _port_node_id(src_port, "input")
        else:
            continue
        dst_id = _flop_node_id(dst)
        width = x.get("width", 1)
        if x.get("async_per_sdc"):
            buf.write(f'  {src_id} -. "⚠ async · {width}b" .-> {dst_id}\n')
        else:
            buf.write(f"  {src_id} --- {dst_id}\n")
        edge_idx += 1

    # Clock-network crossings (schema 1.1+). A foreign-domain flop
    # driving a clock-mux select or ICG enable whose output reaches
    # the destination flop's CLK pin — the CDC-010 hazard. Drawn
    # with a thick arrow so it stands apart from data crossings.
    clock_net_crossings = sorted(
        map_data.get("clock_network_crossings", []),
        key=lambda c: (
            c.get("src_flop", ""),
            c.get("dst_flop", ""),
            c.get("control_cell", ""),
        ),
    )
    clock_net_edge_indices: list[int] = []
    for x in clock_net_crossings:
        src = x.get("src_flop")
        dst = x.get("dst_flop")
        if not src or not dst:
            continue
        src_id = _flop_node_id(src)
        dst_id = _flop_node_id(dst)
        kind = x.get("control_kind", "mux-select")
        pin = x.get("control_pin", "?")
        kind_word = "mux" if kind == "mux-select" else "gate"
        buf.write(f'  {src_id} ==> |"⚡ clk-ctrl ({kind_word} {pin})"| {dst_id}\n')
        clock_net_edge_indices.append(edge_idx)
        edge_idx += 1

    # Legend. One entry per clock (rect = flop shape, fill = clock
    # color), plus a stadium entry for the port shape, plus paired
    # nodes demonstrating sync vs async edge styles. Skipped on
    # single-clock designs where the legend is more noise than help.
    has_unassigned_port = any(not p.get("clock") for p in ports)
    legend_emitted = len(palette_order) >= 2 or has_unassigned_port
    legend_node_ids: list[str] = []
    if legend_emitted:
        buf.write('  subgraph rb_legend["Legend"]\n')
        buf.write("    direction LR\n")
        clock_meta = {c["name"]: c for c in clocks}
        for name in palette_order:
            cls = clock_class[name]
            meta = clock_meta.get(name)
            if name in orphans:
                label = f"flop · {name} (undeclared)"
            elif meta and isinstance(meta.get("period"), (int, float)):
                label = f"flop · {name} ({meta['period']} ns)"
            else:
                label = f"flop · {name}"
            node_id = f"lg_clk_{_safe_id(name)}"
            buf.write(f'    {node_id}["{label}"]:::{cls}\n')
            legend_node_ids.append(node_id)
        buf.write('    lg_port[/"port (no clock)"/]:::port_unassigned\n')
        buf.write('    lg_sync_a[" "]:::ckcls_legend_neutral\n')
        buf.write('    lg_sync_b[" "]:::ckcls_legend_neutral\n')
        buf.write('    lg_async_a[" "]:::ckcls_legend_neutral\n')
        buf.write('    lg_async_b[" "]:::ckcls_legend_neutral\n')
        buf.write('    lg_sync_a --- |"sync crossing"| lg_sync_b\n')
        buf.write('    lg_async_a -. "⚠ async crossing" .-> lg_async_b\n')
        buf.write("  end\n")
        legend_node_ids += [
            "lg_port",
            "lg_sync_a",
            "lg_sync_b",
            "lg_async_a",
            "lg_async_b",
        ]

    # Strip the default mermaid theme tint from every subgraph box —
    # the only color in the diagram should come from per-clock node
    # fills; the subgraph wrappers are grouping devices.
    subgraph_ids = [_clock_subgraph_id(c["name"]) for c in clocks]
    subgraph_ids += [_clock_subgraph_id(o) for o in orphans]
    if legend_emitted:
        subgraph_ids.append("rb_legend")
    for sgid in subgraph_ids:
        buf.write(f"  style {sgid} fill:none,stroke:#cbd5e1\n")
    for nid in legend_node_ids:
        buf.write(f"  style {nid} font-size:11px\n")

    # Amber warning hue on every clock-network crossing arrow so the
    # CDC-010 hazard reads as a "danger" relationship distinct from
    # the muted data crossings. Applied via ``linkStyle`` which
    # targets edges by 0-indexed declaration order (tracked above).
    if clock_net_edge_indices:
        idx_list = ",".join(str(i) for i in clock_net_edge_indices)
        buf.write(
            f"  linkStyle {idx_list} stroke:#b45309,stroke-width:2.5px,color:#b45309\n"
        )

    # classDefs at the bottom so they're easy to find. One per clock
    # used in the diagram, plus the fallback for ports with no
    # declared clock domain.
    for idx, name in enumerate(palette_order):
        fill, stroke = _CLOCK_PALETTE[idx % len(_CLOCK_PALETTE)]
        buf.write(
            f"  classDef {clock_class[name]} "
            f"fill:{fill},stroke:{stroke},stroke-width:1.5px,color:#0f172a\n"
        )
    buf.write(
        f"  classDef port_unassigned "
        f"fill:{_FALLBACK_FILL},stroke:{_FALLBACK_STROKE},color:#0f172a\n"
    )
    # Neutral grey for legend edge-style demonstrator nodes. Tiny
    # placeholder squares so the edge labels dominate.
    buf.write(
        "  classDef ckcls_legend_neutral "
        "fill:#ffffff,stroke:#cbd5e1,stroke-width:1px,color:#0f172a\n"
    )
    buf.write("```\n")
    return buf.getvalue()


# --- helpers ----------------------------------------------------------------


def _check_schema(map_data: dict[str, Any]) -> None:
    sv = str(map_data.get("schema_version", ""))
    if not sv:
        raise RenderError("input is missing 'schema_version'")
    major = sv.split(".", 1)[0]
    if major != str(SUPPORTED_SCHEMA_MAJOR):
        raise RenderError(
            f"unsupported domain-map schema major {major!r}; "
            f"this renderer understands v{SUPPORTED_SCHEMA_MAJOR}.x"
        )


def _all_clocks(map_data: dict[str, Any]) -> list[dict[str, Any]]:
    """Concatenate ``clocks`` and ``generated_clocks``, sorted by name.

    Generated clocks fall through with whatever fields they carry — we
    only ever read ``name`` and ``period`` so missing keys are fine.
    """
    out = list(map_data.get("clocks", [])) + list(map_data.get("generated_clocks", []))
    out.sort(key=lambda c: str(c.get("name", "")))
    return out


def _group_flops_by_clock(
    flops: list[dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    by_clock: dict[str, list[dict[str, Any]]] = {}
    for fd in flops:
        clk = fd.get("clock") or ""
        by_clock.setdefault(clk, []).append(fd)
    for clk in by_clock:
        by_clock[clk].sort(key=lambda e: str(e.get("instance_path", "")))
    return by_clock


def _clock_header(clk: dict[str, Any]) -> str:
    name = clk.get("name", "?")
    period = clk.get("period")
    if isinstance(period, (int, float)):
        return f"{name} · {period} ns"
    return str(name)


def _clock_subgraph_id(clock_name: str) -> str:
    return "clk_" + _safe_id(clock_name)


def _clock_class_name(clock_name: str) -> str:
    return "ckcls_" + _safe_id(clock_name)


def _flop_node_id(instance_path: str) -> str:
    # Mermaid node ids must be id-like; instance paths contain ``$`` /
    # ``.`` / ``/`` which are unsafe. Hash for collision-resistance,
    # short prefix for human-greppability.
    h = hashlib.sha256(instance_path.encode("utf-8")).hexdigest()[:8]
    return f"f_{h}"


def _port_node_id(port_name: str, kind: str) -> str:
    return f"p_{kind[:2]}_{_safe_id(port_name)}"


def _emit_port_line(
    buf: StringIO, port: dict[str, Any], cls: str, *, indent: str
) -> None:
    port_id = _port_node_id(port["port"], port.get("kind", "input"))
    kind = port.get("kind", "input")
    marker = "in" if kind == "input" else "out"
    buf.write(f'{indent}{port_id}[/"{port["port"]}⟨{marker}⟩"/]:::{cls}\n')


def _safe_id(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    if not out or not (out[0].isalpha() or out[0] == "_"):
        out.insert(0, "_")
    return "".join(out)


def _flop_label(fd: dict[str, Any], top: str) -> str:
    path = str(fd.get("instance_path", "?"))
    # Strip the top module prefix to keep labels short. ``top.foo.bar``
    # becomes ``foo.bar``; the lone top stays as-is.
    prefix = f"{top}."
    short = path[len(prefix) :] if path.startswith(prefix) else path
    loc = fd.get("location") or {}
    line = loc.get("start_line")
    if isinstance(line, int):
        return f"{short}<br/><i>sv:{line}</i>"
    return short
