// Negative-case fixture: an async-reset signal generated by a flop in
// the source clock domain is wired directly into the asynchronous
// reset pin of a flop in a different clock domain. The reset is
// asserted immediately but its deassertion edge is unrelated to
// dst_clk, so dst_q's recovery may violate timing and corrupt the
// flop. Should trip CDC-007.

module bad_reset_crossing (
    input  logic src_clk,
    input  logic dst_clk,
    input  logic global_rst_n,
    input  logic kill_req,
    input  logic d_in,
    output logic q_out
);

    // Reset signal is registered in the source clock domain.
    logic src_kill_n;
    always_ff @(posedge src_clk or negedge global_rst_n) begin
        if (!global_rst_n) src_kill_n <= 1'b0;
        else               src_kill_n <= ~kill_req;
    end

    // BAD: src-domain flop output used as async reset of a dst-domain
    // flop with no reset synchronizer in dst_clk.
    logic dst_q;
    always_ff @(posedge dst_clk or negedge src_kill_n) begin
        if (!src_kill_n) dst_q <= 1'b0;
        else             dst_q <= d_in;
    end

    assign q_out = dst_q;

endmodule
