"""Generate a `README.md` for every fixture under `tests/fixtures/`.

The README embeds a mermaid clock-domain diagram produced by
``rtl-buddy-cdc render`` over the fixture's own netlist + SDC. The
prose comes from the leading ``//`` comment block on the fixture's
primary SystemVerilog file.

Run from the repo root:

    uv run python scripts/gen_fixture_docs.py            # write all
    uv run python scripts/gen_fixture_docs.py --check    # diff-only

See issue rtl-buddy-cdc#164 for the design discussion.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURES = REPO_ROOT / "tests" / "fixtures"

GENERATOR_TAG = "<!-- generator: scripts/gen_fixture_docs.py -->"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any README would change (CI drift check).",
    )
    ap.add_argument(
        "--only",
        action="append",
        default=[],
        help="Limit to specific fixture dir-names (repeatable).",
    )
    args = ap.parse_args()

    fixtures = sorted(p for p in FIXTURES.iterdir() if p.is_dir())
    if args.only:
        wanted = set(args.only)
        fixtures = [f for f in fixtures if f.name in wanted]

    drift = 0
    written = 0
    for fix in fixtures:
        try:
            body = _build_readme(fix)
        except _SkipFixture as e:
            print(f"skip  {fix.name}: {e}", file=sys.stderr)
            continue

        readme = fix / "README.md"
        current = readme.read_text() if readme.exists() else None
        # If a human-curated README exists without our generator tag,
        # leave it alone. (See `ip_cdc_handshake/README.md`.)
        if current is not None and GENERATOR_TAG not in current:
            print(f"keep  {fix.name}: hand-written README untouched")
            continue

        if current == body:
            continue

        if args.check:
            print(f"drift {fix.name}", file=sys.stderr)
            drift += 1
        else:
            readme.write_text(body)
            written += 1
            print(f"write {fix.name}")

    if args.check and drift:
        print(f"\n{drift} README(s) out of date — run without --check", file=sys.stderr)
        return 1
    if not args.check:
        print(f"\n{written} README(s) updated")
    return 0


class _SkipFixture(Exception):
    pass


def _build_readme(fix: Path) -> str:
    primary_sv = fix / f"{fix.name}.sv"
    sdc = fix / f"{fix.name}.sdc"
    netlist = fix / f"{fix.name}.json"

    if not primary_sv.exists():
        raise _SkipFixture(f"missing {primary_sv.name}")
    if not sdc.exists():
        raise _SkipFixture(f"missing {sdc.name}")

    description = _leading_comment(primary_sv)
    netlist_arg = netlist if netlist.exists() else None
    map_data, mermaid = _render(netlist_arg, sdc, primary_sv, fix.name)
    status = _status_for(fix.name)
    facts = _facts_line(map_data)

    files = sorted(
        p.name for p in fix.iterdir() if p.is_file() and p.name != "README.md"
    )
    file_lines = "\n".join(f"- `{name}`" for name in files)

    return f"""# Fixture: `{fix.name}`

{GENERATOR_TAG}

{description}

- **Status:** {status}
- **Top module:** `{fix.name}`
{facts}

## Clock-domain map

{mermaid}
## Files

{file_lines}

---
*Generated by `scripts/gen_fixture_docs.py` — re-run after editing the SV/SDC/netlist.*
"""


def _leading_comment(sv: Path) -> str:
    """Return the leading ``//`` comment block as markdown.

    Comment lines are split into paragraphs at blank ``//`` lines. A
    paragraph rendered as prose collapses to a single joined line;
    paragraphs containing any indented (ASCII-art, bullet, code-like)
    line are emitted as a fenced ``text`` block so their layout
    survives.
    """
    lines: list[str] = []
    for raw in sv.read_text().splitlines():
        stripped = raw.lstrip()
        if not stripped:
            if lines:
                break
            continue
        if stripped.startswith("//"):
            # Drop the leading "//" but keep any internal indentation
            # so diagrams/bullets render correctly downstream.
            body = stripped[2:]
            if body.startswith(" "):
                body = body[1:]
            lines.append(body)
        else:
            break
    if not lines:
        return (
            "_(no leading comment in the SV file — add one to populate this README.)_"
        )

    paras: list[list[str]] = [[]]
    for line in lines:
        if not line.strip():
            if paras[-1]:
                paras.append([])
        else:
            paras[-1].append(line)

    rendered: list[str] = []
    for para in paras:
        if not para:
            continue
        if any(line.startswith(" ") for line in para):
            block = "\n".join(para)
            rendered.append(f"```text\n{block}\n```")
        else:
            rendered.append(" ".join(line.strip() for line in para))
    return "\n\n".join(rendered)


def _render(netlist: Path | None, sdc: Path, sv: Path, top: str) -> tuple[dict, str]:
    """Run ``analyze``/``lint`` to get a domain map, then ``render``; return (map, mermaid).

    When the fixture has a committed Yosys netlist (the common case)
    we use ``analyze`` over it. When it doesn't (slang-elaboration
    fixtures like ``good_gen_clock_internal_pin``) we fall back to
    ``lint``, which elaborates from the SV source via the Yosys
    frontend — this requires ``yosys`` in PATH at generation time.
    """
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as tmp:
        map_path = Path(tmp.name)
    try:
        if netlist is not None and netlist.exists():
            cmd: list[str] = [
                "uv",
                "run",
                "rtl-buddy-cdc",
                "analyze",
                "--netlist",
                str(netlist),
                "--sdc",
                str(sdc),
                "--emit-domain-map",
                str(map_path),
                "--no-findings",
            ]
        else:
            cmd = [
                "uv",
                "run",
                "rtl-buddy-cdc",
                "lint",
                "--top",
                top,
                "--sdc",
                str(sdc),
                "--frontend",
                "yosys",
                "--emit-domain-map",
                str(map_path),
                "--no-findings",
                str(sv),
            ]
        elab = subprocess.run(
            cmd,
            cwd=REPO_ROOT,
            capture_output=True,
        )
        if elab.returncode != 0:
            # Plugin-only fixtures (e.g. those importing a SystemVerilog
            # package, which `read_verilog -sv` rejects and only the
            # yosys-slang `read_slang` plugin elaborates) can't be doc'd
            # by the plain Yosys frontend. Skip rather than abort the
            # whole run — the plugin path is covered by a gated test.
            raise _SkipFixture("plain yosys frontend could not elaborate it")
        map_data = json.loads(map_path.read_text())
        result = subprocess.run(
            [
                "uv",
                "run",
                "rtl-buddy-cdc",
                "render",
                "--map",
                str(map_path),
                "--format",
                "mermaid",
            ],
            check=True,
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
        )
        mermaid = result.stdout
        if not mermaid.endswith("\n"):
            mermaid += "\n"
        return map_data, mermaid
    finally:
        map_path.unlink(missing_ok=True)


def _status_for(name: str) -> str:
    if name.startswith("bad_"):
        return "negative — analyzer must report a violation"
    if name.startswith("good_"):
        return "positive — textbook fix; analyzer must stay silent"
    if name.startswith("marked_"):
        return "marker — exercises an SV attribute (`cdc_sync` / `cdc_gray` / …)"
    return "auxiliary"


def _facts_line(map_data: dict) -> str:
    clocks = list(map_data.get("clocks", [])) + list(
        map_data.get("generated_clocks", [])
    )
    clocks.sort(key=lambda c: str(c.get("name", "")))
    if clocks:
        rendered = ", ".join(f"`{c.get('name', '?')}` ({_period(c)})" for c in clocks)
        clk_line = f"- **Clocks:** {rendered}"
    else:
        clk_line = "- **Clocks:** _(none declared)_"

    crossings = map_data.get("crossings", [])
    async_count = sum(1 for c in crossings if c.get("async_per_sdc"))
    sync_count = len(crossings) - async_count
    cross_line = (
        f"- **Crossings:** {len(crossings)} structural "
        f"({async_count} async-per-SDC, {sync_count} sync)"
    )
    return f"{clk_line}\n{cross_line}"


def _period(clk: dict) -> str:
    p = clk.get("period")
    if isinstance(p, (int, float)):
        return f"{p} ns"
    return "no period"


if __name__ == "__main__":
    raise SystemExit(main())
